refactor: add assertion for tags to prevent human error
Signed-off-by: K3rnelPan1c <69395733+k3rnelpan1c-dev@users.noreply.github.com>

Co-authored-by: Niklas <nscuro@protonmail.com>
Signed-off-by: K3rnelPan1c <69395733+k3rnelpan1c-dev@users.noreply.github.com>

diff --git a/.github/workflows/ci-publish.yaml b/.github/workflows/ci-publish.yaml
--- a/.github/workflows/ci-publish.yaml
+++ b/.github/workflows/ci-publish.yaml
@@ -14,6 +14,13 @@ jobs:
     outputs:
       version: ${{ steps.parse.outputs.version }}
     steps:
+      - name: Assert ref type
+        run: |-
+          if [[ "$GITHUB_REF_TYPE" != "tag" ]]; then
+            echo "::error::Publishing is only supported for tags!"
+            exit 1
+          fi
+
       - name: Checkout Repository
         uses: actions/checkout@v3.0.2
 
